# Pauli matrices

Crucial for quantum computing. All operations of a quantum computer are commonly represented with Pauli Matrices. However, lets take a step towards the mathematical representation of the wavefunction first.

## The wavefunction
The wavefunction is a central object in quantum mechanics. Out of many equivalent representations of the wavefunction it is very commont to represent the wavefunction with a vector: $$\psi= \alpha\begin{pmatrix} 1 \\ 0 \end{pmatrix} + \beta\begin{pmatrix} 0 \\ 1 \end{pmatrix}$$

Recall that the meaning of the wavefunction is that of a probability density. As no probability can be higher or lower than one, the wavefunction $\psi$ is normalized ; hence, $$\alpha^{*}\alpha + \beta^{*}\beta=1 .$$

The constants $\alpha$ and $\beta$ can take any value between $0$ and $1$. For instance, such a state where $\alpha=1$ and $\beta=0$ corresponds to such a state where the vector "one up" is present in the "mixture" of vectors while the vector "one down" is absent. And vice-versa. However nothing is preventing you to have $\alpha=\frac{1}{\sqrt{2}}$ and $\beta=\frac{1}{\sqrt{2}}$ - the normalization condition would still be fulfiled.

In its shortest quantum computing is the art of manipulating wavefunctions. The wavefunction above is the simples example of a one qubit wavefunction. 

# again about Pauli Matrices
---
Spin is an inherent property which particles have in quantum mechanics. When for instance electrons are inside a magnetic field they would behave like small magnets. Spin up and spin down is the syntax commonly used with respects how this small magnets behave in a magnetic field. 


In quantum mechanics the behaviour of particles in a magnetic field is mathematically described by Pauli matrices. The pauli matrices of spin-1/2 can be presented as 
$$\sigma_x = \begin{pmatrix} 0 & 1 \\ 1 & 0 \end{pmatrix} , $$ 
$$\sigma_y = \begin{pmatrix} 0 & -i \\ i & 0 \end{pmatrix} , $$
$$\sigma_z = \begin{pmatrix} 1 & 0 \\ 0 & -1 \end{pmatrix} . $$
\
Also, the trace of a matrix means the sum of diagonal terms of a matrix.
Then, $$Tr(\sigma_x)=Tr(\sigma_y)=Tr(\sigma_z)=0$$

Hence, $$\langle\psi|\sigma_x|\psi\rangle=\alpha^{*}\beta+\beta^{*}\alpha , $$

if $\alpha=1$ and $\beta=0$ this means that one has only spin polarized up (the $z$-axis defines up and down). The total amount of spin along the perpendicular direction ($x$ is therefore 0)
$$\langle\psi|\sigma_z|\psi\rangle=\alpha^{*}\alpha - \beta^{*}\beta , $$
and
$$\langle\psi|\frac{\sigma_x+\sigma_z}{\sqrt{3}}|\psi\rangle=\frac{\alpha^{*}\beta+\beta^{*}\alpha+\alpha^{*}\alpha - \beta^{*}\beta}{\sqrt{3}}. $$

In [1]:
import numpy as np

In [2]:
sx = np.matrix([[0,1.],[1.,0]])
sy = np.matrix([[0,-1j],[1j,0]])
sz = np.matrix([[1.,0],[0,-1.]])

In [3]:
print(np.trace(sx))
print(np.trace(sy).real)
print(np.trace(sz))

0.0
0.0
0.0


## Unitary property
What is a unitary matrix? It is such a matrix which you multiply with its transpose-conjugate and get a unit matrix
It is important to point out that 
$$\sigma_x^{\dagger}\sigma_x = \sigma_y^{\dagger}\sigma_y = \sigma_z^{\dagger}\sigma_z = \boldsymbol{I},$$
where $\dagger$ represents the hermitian matrix.
Hence, $\sigma_x$, $\sigma_y$, and $\sigma_z$ are unitary matrice. This also indicates that
$$\sigma_i^{-1} = \sigma_{i}^{\dagger},$$
where $i=x,y,z$

In [4]:
sx.getH()@sx

matrix([[1., 0.],
        [0., 1.]])

In [5]:
sy.getH()@sy

matrix([[1.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j]])

In [6]:
sz.getH()@sz

matrix([[1., 0.],
        [0., 1.]])

## Comutator and Anti-comutator

It is also useful to introduce comutator and anti-comutator.
For any two given operators $\hat{A}$, $\hat{B}$, the comutator of $\hat{A}$ and $\hat{B}$ can be expressed as
$$[\hat{A},\hat{B}]=\hat{A}\hat{B}-\hat{B}\hat{A} .$$
While the anti-comutator of $\hat{A}$ and $\hat{B}$ can be expressed as
$$\{\hat{A},\hat{B}\}=\hat{A}\hat{B}+\hat{B}\hat{A} .$$

Considering $\sigma_x$, $\sigma_y$, and $\sigma_z$, we have
$$[\sigma_x, \sigma_y]= 2i\sigma_z \;, \; [\sigma_y, \sigma_z]= 2i\sigma_x\;, \; [\sigma_z, \sigma_x]= 2i\sigma_y $$

In [7]:
print(sx@sy - sy@sx)
print(sy@sz - sz@sy)
print(sz@sx - sx@sz)

[[0.+2.j 0.+0.j]
 [0.+0.j 0.-2.j]]
[[0.+0.j 0.+2.j]
 [0.+2.j 0.+0.j]]
[[ 0.  2.]
 [-2.  0.]]


And
$$\{\sigma_x, \sigma_y\}= \{\sigma_y, \sigma_z\}= \{\sigma_z, \sigma_x\}= \begin{pmatrix} 0 & 0 \\ 0 & 0 \end{pmatrix}$$

In [20]:
print(sx@sy + sy@sx)
print(sy@sz + sz@sy)
print(sz@sx + sx@sz)

[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
[[0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j]]
[[0. 0.]
 [0. 0.]]


## Tensor product

Tensor product is a useful operation in quantum circuits. Suppose we have matrice $A$ and $B$. And both $A$ and $B$ are 2 by 2 matrice.
$$A\otimes B = \begin{pmatrix} A_{11}\begin{pmatrix} B_{11} & B_{12} \\ B_{21} & B_{22} \end{pmatrix} & A_{12}\begin{pmatrix} B_{11} & B_{12} \\ B_{21} & B_{22} \end{pmatrix} \\ 
A_{21}\begin{pmatrix} B_{11} & B_{12} \\ B_{21} & B_{22} \end{pmatrix} & A_{22}\begin{pmatrix} B_{11} & B_{12} \\ B_{21} & B_{22} \end{pmatrix} \end{pmatrix}.$$
And the result will become a 4 by 4 matrix. 

In [8]:
print(np.kron(sx,sz))

[[ 0.  0.  1.  0.]
 [ 0. -0.  0. -1.]
 [ 1.  0.  0.  0.]
 [ 0. -1.  0. -0.]]


In [9]:
print(np.kron(sz,sx))

[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0. -0. -1.]
 [ 0.  0. -1. -0.]]


# Pauli matrix and spin 1/2 quantum particles

Spin-1/2 quantum particles can be described by 2 'quantum numbers', including $S=1/2$ with $\mu_s = \pm 1/2$. The state, $|S=1/2;\mu_s =1/2\rangle$ or $|+\rangle$, is defined as $\begin{pmatrix} 1 \\ 0 \end{pmatrix}$ while the state, $|S=1/2;\mu_s=-1/2\rangle$ or $|-\rangle$, is defined as $\begin{pmatrix} 0 \\ 1 \end{pmatrix}$.
\
In practice, instead of $S_x$, $S_y$, and $S_z$($\sigma_x$, $\sigma_y$, and $\sigma_z$), the following operators are used:
$$\sigma_+=\sigma_x+i\sigma_y,\; \sigma_{-}=\sigma_x-i\sigma_y,\; \sigma_z .$$


This is a ket |> - mathematically this represents a vector
This is a bra <| - mathematically this represent a vector transposed

The wavefunction is also a "ket" or a "bra". So you would often write $|\psi\rangle$ and $\langle \psi|$

# Handin:
- find matrix representation of $\sigma_+$, and $\sigma_-$.
- How do you understand $\sigma_+$, and $\sigma_-$?

# Solution

$$\sigma_+ = \begin{pmatrix} 0 & 1 \\ 0 & 0 \end{pmatrix}$$
$$\sigma_- = \begin{pmatrix} 0 & 1 \\ 0 & 0 \end{pmatrix}$$

Both $\sigma_+$ and $\sigma_-$ are known as "ladder operators":
$$\sigma_+|-\rangle = |+\rangle$$
and
$$\sigma_-|+\rangle = |-\rangle$$
Since we only have two states, this implies
$$\sigma_+|+\rangle = 0$$
and
$$\sigma_-|-\rangle = 0$$
